voting_site/urls.py
from django.contrib import admin
from django.urls import path
from voting_app import views
from voting_site import settings
from django.conf.urls.static import static

handler404 = 'voting_app.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('voting/', views.voting_detail),
    path('', views.voting_list, name='voting_list'),
    path('<int:voting_id>/', views.voting_detail, name='voting_detail'),
    path('accounts/login/', views.user_login, name='login'),
    path('accounts/logout/', views.user_logout, name='logout'),
    path('create_voting/', views.create_voting, name='create_voting'),
    path('accounts/register/', views.user_register, name='register'),
    path('edit_voting/<int:voting_id>/', views.edit_voting, name='edit_voting'),
    path('user_options_list/<int:user_id>/', views.user_votes, name='user_options_list'),
    path('create_claim/<int:voting_id>/', views.create_claim, name='create_claim'),
    path('search/', views.search, name='search'),
    path('profile/<str:username>', views.user_page, name='profile'),
    path('publications/', views.publications, name='publications'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Voting(models.Model):
  title = models.CharField(max_length=255)
  description = models.TextField()
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='voting_images/', blank=True, null=True)
  voting_type = models.CharField(max_length=255, default='SOME STRING')


class Option(models.Model):
  voting_id = models.ForeignKey(Voting, on_delete=models.CASCADE)
  content = models.CharField(max_length=255)


class Vote(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  option = models.ForeignKey(Option, on_delete=models.CASCADE)


class Claim(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    voting = models.ForeignKey(Voting, on_delete=models.CASCADE)

voting_app/forms.py
from django import forms
from .models import Claim, Voting, Option

class VotingForm(forms.ModelForm):
    voting_type = forms.ChoiceField(
        choices=[('single', 'One of Many'), ('multiple', 'Multiple Choices')],
        widget=forms.RadioSelect(),
        initial='single'
    )

    class Meta:
        model = Voting
        fields = ['title', 'description', 'image', 'voting_type']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(VotingForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        voting = super(VotingForm, self).save(commit=False)
        if self.request:
            voting.author = self.request.user
        voting.save()

        options_input = self.data.getlist('option-field')
        for option_text in options_input:
            Option.objects.create(voting_id=voting, content=option_text.strip())

        return voting


class ClaimForm(forms.ModelForm):
    class Meta:
        model = Claim
        fields = ['body', 'voting']

    def __init__(self, user, *args, **kwargs):
        super(ClaimForm, self).__init__(*args, **kwargs)
        self.fields['voting'].queryset = Voting.objects.filter(author=user)
        self.fields['voting'].widget = forms.HiddenInput()  # Скрыть поле voting, так как значение уже установлено

    def clean_voting(self):
        return self.cleaned_data['voting']

    def save(self, commit=True):
        claim = super(ClaimForm, self).save(commit=False)
        claim.user = self.user
        if commit:
            claim.save()
        return claim

voting_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.urls import reverse
from voting_app.forms import ClaimForm, VotingForm
from .models import Claim, Voting, Option, Vote
from django.contrib.auth.decorators import login_required


@login_required
def voting_list(request):
    votings = Voting.objects.all()
    return render(request, 'index.html', {'votings': votings})


@login_required
def voting_detail(request, voting_id):
    voting = get_object_or_404(Voting, pk=voting_id)
    options = Option.objects.filter(voting_id=voting)
    existing_votes = Vote.objects.filter(user=request.user, option__voting_id=voting)
    claims = Claim.objects.filter(voting_id=voting)
    voting_type = voting.voting_type
    if request.method == 'POST':
        selected_options_ids = request.POST.getlist('options')
        selected_options = Option.objects.filter(id__in=selected_options_ids)
        if not existing_votes.exists() and selected_options.exists():
            for option in selected_options:
                Vote.objects.create(user=request.user, option=option)
        vote_percents = {}
        votes_summ = 0
        users = []
        for option in options:
            for vote in Vote.objects.filter(option_id=option.id):
                if vote.user not in users:
                    users.append(vote.user)
        for option in options:
            vote_summ = Vote.objects.filter(option_id=option.id).count()
            if len(users) > 0:
                vote_percents[option.id] = int(vote_summ / max(1, len(users)) * 100)
            else:
                vote_percents[option.id] = 0
        return render(request, 'voting.html', {'voting': voting, 'options': options, 'already_voted': 1, 'vote_percents': vote_percents})
    else:
        return render(request, 'voting.html', {'voting': voting, 'options': options, 'already_voted': 0, 'voting_type': voting_type, 'claims': claims})






def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('voting_list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('voting_list')


def create_voting(request):
    if request.method == 'POST':
        form = VotingForm(request.POST, request.FILES, request=request)
        voting_type = request.POST['voting_type']
        if form.is_valid():
            form.save()
    else:
        form = VotingForm(request=request)

    context = {'form': form}
    return render(request, 'create_voting.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('voting_list')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

@login_required
def edit_voting(request, voting_id):
    voting = get_object_or_404(Voting, pk=voting_id)
    if request.user != voting.author:
        return redirect('voting_list')

    if request.method == 'POST':
        form = VotingForm(request.POST, instance=voting, request=request)
        if form.is_valid():
            form.save()
            return redirect('voting_list')
    else:
        form = VotingForm(instance=voting, request=request)

    return render(request, 'edit.html', {'form': form, 'voting': voting})

@login_required
def user_votes(request, user_id):
    user_votes = Vote.objects.filter(user=user_id)
    user_votes_data = list()
    for vote in user_votes:
        option = get_object_or_404(Option, id=vote.option_id)
        voting = get_object_or_404(Voting, id=option.voting_id_id)
        user_votes_data.append({
            'voting_title': voting.title,
            'voting_author': voting.author,
            'option_content': option.content,
        })
    context = {
        'user_votes_data': user_votes_data,
    }
    return render(request, 'user_options_list.html', context)

@login_required
def create_claim(request, voting_id):
    voting = Voting.objects.get(pk=voting_id)

    if request.method == 'POST':
        form = ClaimForm(request.user, request.POST, initial={'voting': voting})
        if form.is_valid():
            form.user = request.user
            form.save()
            return redirect('voting_list')
    else:
        form = ClaimForm(request.user, initial={'voting': voting})

    return render(request, 'create_claim.html', {'form': form})


def search(request):
    if request.method == 'POST':
        voting_id = request.POST['search']
        try:
            destination_url = reverse('voting_detail', kwargs={'voting_id': voting_id})
            return redirect(destination_url)
        except:
            return redirect('voting_list')
    else:
        return redirect('voting_list')

@login_required
def user_page(request, username):
    user = User.objects.get(username=username)
    if request.user == user:
        return render(request, 'profile.html', {'user': user})
    else:
        return redirect('voting_list')


@login_required
def publications(request):
    user_voting = Voting.objects.filter(author=request.user)
    return render(request, 'publications.html', {'user_voting': user_voting})



def handler404(request, exception):
    return render(request, '404.html', status=404)

voting_app/templates/NavBar.html
{% load static %}
<div class="nav">
        <div class="nav__container">
            <div class="nav_logo">
                <div class="nav_logo_container">
                    <a class="nav_logo-link" href="" title="SpaceAlien">
                        <div class="nav_logo-svg_container">
                            <img class="nav_logo-svg" src="{% static 'data\SpaceAlien_logo.svg' %}" alt="">
                        </div>
                    </a>
                </div>
            </div>
            <div class="menu__container">
                <nav class="menu__link-bar">
                    <ul class="menu__list">
                        <li class="menu__item active" role="listitem">
                            <a class="menu__link" href="/">
                                <div class="menu__link_container">
                                    <div class="menu__icon">
                                        <img src="{% static 'data\home.svg' %}" alt="">
                                    </div>
                                    <div class="menu__title">
                                        Главная
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="menu__item no_active" role="listitem">
                            <a class="menu__link" href="">
                                <div class="menu__link_container">
                                    <div class="menu__icon">
                                        <img src="{% static 'data\notifications.svg' %}" alt="">
                                    </div>
                                    <div class="menu__title">
                                        Уведомления
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="menu__item no_active" role="listitem">
                            <a class="menu__link" href="/publications/">
                                <div class="menu__link_container">
                                    <div class="menu__icon">
                                        <img src="{% static 'data\article.svg' %}" alt="">
                                    </div>
                                    <div class="menu__title">
                                        Публикации
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="menu__item no_active" role="listitem">
                            <a class="menu__link" href="/profile/{{request.user.username}}">
                                <div class="menu__link_container">
                                    <div class="menu__icon">
                                        <img src="{% static 'data\account.svg' %}" alt="">
                                    </div>
                                    <div class="menu__title">
                                        Аккаунт
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="menu__item no_active" role="listitem">
                            <a class="menu__link" href="/about_us/">
                                <div class="menu__link_container">
                                    <div class="menu__icon">
                                        <img src="{% static 'data\about.svg' %}" alt="">
                                    </div>
                                    <div class="menu__title">
                                        О нас
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

voting_app/templates/already.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
a    <p>Вы уже проголосовали в этом опросе</p>
    <a href="{% url 'voting_list' %}">Перейти к списку голосований</a>
  </body>
</html>

voting_app/templates/create_claim.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Claim</title>
</head>
<body>
    <h2>Create Claim</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

voting_app/templates/create_voting.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create a New Voting</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body class="container mt-5">
    <h2 class="mb-4">Create a New Voting</h2>
    <form method="post" action="{% url 'create_voting' %}" id="voting-form" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.as_p }}
      </div>
      <div class="mb-3" id="options-container">
        <label for="id_options" class="form-label">Options:</label>
        <div class="options-wrapper">
          <input
            type="text"
            name="option-field"
            class="form-control option-field"
            required
          />
          <button type="button" class="btn btn-primary add-option-btn">Add Option</button>
        </div>
      </div>
      <button type="submit" class="btn btn-success">Create Voting</button>
    </form>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const optionsContainer = document.getElementById("options-container");
        const addOptionBtn = document.querySelector(".add-option-btn");

        addOptionBtn.addEventListener("click", function () {
          const newInput = document.createElement("input");
          newInput.type = "text";
          newInput.name = "option-field";
          newInput.className = "form-control option-field";
          newInput.required = true;

          const wrapper = document.createElement("div");
          wrapper.className = "options-wrapper mt-2";
          wrapper.appendChild(newInput);

          optionsContainer.appendChild(wrapper);
        });
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-1q8w5EXr1wGPJkGN+6iNl6jZilxLcweCdSQBIof2IbAL6x70z2ROewpRDMcH+8xq" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></script>
  </body>
</html>

voting_app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h2>Edit Voting</h2>
    <form
      method="post"
      action="{% url 'edit_voting' voting.id %}"
      id="voting-form"
    >
      {% csrf_token %} {{ form.as_p }}
      <div id="options-container">
        <label for="id_options">Options:</label>
        {% for option in voting.option_set.all %}
        <div class="options-wrapper">
          <input
            type="text"
            name="options-field"
            class="options-field"
            value="{{ option.content }}"
            required
          />
        </div>
        {% endfor %}
        <button type="button" class="add-option-btn">Add Option</button>
      </div>
      <button type="submit">Save Changes</button>
    </form>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const optionsContainer = document.getElementById("options-container");
        const addOptionBtn = document.querySelector(".add-option-btn");

        addOptionBtn.addEventListener("click", function () {
          const newInput = document.createElement("input");
          newInput.type = "text";
          newInput.name = "option-field";
          newInput.className = "option-field";
          newInput.required = true;

          const wrapper = document.createElement("div");
          wrapper.className = "options-wrapper";
          wrapper.appendChild(newInput);

          optionsContainer.appendChild(wrapper);
        });
      });
    </script>
  </body>
</html>

voting_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Главная</title>
    <link rel="stylesheet" href="{% static 'css\index.css' %}" />
    <link rel="stylesheet" href="{% static 'css\menu.css' %}" />
    <link rel="stylesheet" href="{% static 'css\header.css' %}" />
    <link rel="stylesheet" href="{% static 'css\scrollbar.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>
  <body>
    {% include "NavBar.html" %}
    <div class="content">
      <header>
        <form action="/search/" method="post" class="form_search">
          {% csrf_token %}
          <div class="header_search">
            <div class="header_search_container">
              <div class="header__search__input__container">
                <input
                  id="input"
                  class="header__search__input"
                  type="search"
                  autocomplete="off"
                  spellcheck="false"
                  role="combobox"
                  aria-controls="matches"
                  placeholder="Введите поисковый запрос"
                  aria-expanded="false"
                  aria-live="polite"
                  name="search"
                />
              </div>
            </div>
            <div>
              <button type="submit">Найти</button>
            </div>
          </div>
        </form>
        <div class="header__log">
          {% if user.is_authenticated %}
          <div class="header__log__container">
            <a class="header__log-text" href="{% url 'logout' %}">Выйти</a>
          </div>
          {% else %}
          <div class="header__log__container">
            <a class="header__log-text" href="{% url 'login' %}">Войти</a>
          </div>
          {% endif %}
        </div>
      </header>
      <main>
        <div class="cards">
          <a href="{% url 'create_voting' %}">Здесь мог быть ваш новый опрос</a>
          <ul class="card__list">
            {% for voting in votings %}
            <li class="card__item">
              <div class="card__container">
                <div class="card__profile_image">
                  <div class="card__profile_image__conteiner">
                    <img src="{% static 'data\test.png' %}" alt="" />
                  </div>
                </div>
                <div class="card__information">
                  <div class="card__title__container">
                    <div class="card__title">{{ voting.author.username }}</div>
                    <div class="card__type">Опрос</div>
                  </div>
                  <div class="card__description">{{ voting.title }}</div>
                </div>
                <div class="card__more">
                  <a href="{% url 'voting_detail' voting.id %}">
                    <div class="card__more__container">
                      <img src="{% static 'data\more.svg' %}" alt="" />
                    </div>
                  </a>
                </div>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </main>
    </div>
  </body>
</html>

voting_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
    <link rel="stylesheet" href="{% static 'css\login.css' %}" />
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</head>
<body>
    <div class="content">
        <div class="login__form">
            <div class="login__form__logo">
                <img src="{% static 'data\SpaceAlien_logo.svg' %}" alt="">
            </div>
            <div class="login_form_title">Вход</div>
            <form method="post" action="/accounts/login/" id="from">
                {% csrf_token %}
                <div class="login__form__username__container">
                    <div class="login__form__username__container-title">
                        Имя пользователя или адрес электронной почты
                    </div>
                    <div class="login__form__username__container-input">
                        <input type="text" name="username" value="" autofocus autocapitalize="none" autocomplete="username"
                               maxlength="150" required id="id_username">
                    </div>
                    <div class="login__username__error" id="username__error">
                        <div class="login__username__error-logo">
                            <img src="{% static 'data\error.svg' %}" alt="">
                        </div>
                        <div class="login__username__error-title">Введите имя пользователя или адрес электронной почты</div>
                    </div>
                </div>
                <div class="login__form__password__container">
                    <div class="login__from__password__container-title">
                        Пароль
                    </div>
                    <div class="login__from__password__container-input">
                        <input type="password" name="password" autocomplete="current-password" required id="id_password">
                    </div>
                    <div class="login__password__error" id="password__error">
                        <div class="login__password__error-logo">
                            <img src="{% static 'data\error.svg' %}" alt="">
                        </div>
                        <div class="login__password__error-title">Введите пароль</div>
                    </div>
                </div>
                <button id="login" onclick="send_form()">Войти</button>
            </form>
        </div>
    </div>
</body>
</html>

voting_app/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ user.username }}</title>
    <link rel="stylesheet" href="{% static 'css\index.css' %}" />
    <link rel="stylesheet" href="{% static 'css\menu.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css\header.css' %}" />
    <link rel="stylesheet" href="{% static 'css\scrollbar.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>
  <body>
    {% include "NavBar.html" %}
    <div class="content">
      <header>
        <form action="/search/" method="post" class="form_search">
          {% csrf_token %}
          <div class="header_search">
            <div class="header_search_container">
              <div class="header__search__input__container">
                <input
                  id="input"
                  class="header__search__input"
                  type="search"
                  autocomplete="off"
                  spellcheck="false"
                  role="combobox"
                  aria-controls="matches"
                  placeholder="Введите поисковый запрос"
                  aria-expanded="false"
                  aria-live="polite"
                  name="search"
                />
              </div>
            </div>
            <div>
              <button type="submit">Найти</button>
            </div>
          </div>
        </form>
        <div class="header__log">
          {% if user.is_authenticated %}
          <div class="header__log__container">
            <a class="header__log-text" href="{% url 'logout' %}">Выйти</a>
          </div>
          {% else %}
          <div class="header__log__container">
            <a class="header__log-text" href="{% url 'login' %}">Войти</a>
          </div>
          {% endif %}
        </div>
      </header>
      <main>
        <div class="container mt-5">
          <div class="row">
            <div class="col-md-3">
              <div class="text-center">
                <div
                  class="bg-secondary text-light rounded-circle d-inline-block"
                  style="width: 150px; height: 150px; line-height: 150px"
                >
                  <span>У тебя лицо кривое</span>
                </div>
              </div>
            </div>
            <div class="col-md-9 d-flex flex-column justify-content-center">
              <h1>{{ user.username }}'s Profile</h1>
              <p>{{ user.email}}</p>
            </div>
          </div>
        </div>
      </main>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

voting_app/templates/publications.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Публикации</title>
    <link rel="stylesheet" href="{% static 'css\index.css' %}" />
    <link rel="stylesheet" href="{% static 'css\menu.css' %}" />
    <link rel="stylesheet" href="{% static 'css\header.css' %}" />
    <link rel="stylesheet" href="{% static 'css\scrollbar.css' %}" />
</head>
<body>
    {% include "NavBar.html" %}
    <div class="content">
        <header>
            <form action="/search/" method="post" class="form_search">
                {% csrf_token %}
                <div class="header_search">
                    <div class="header_search_container">
                        <div class="header__search__input__container">
                            <input id="input" class="header__search__input" type="search" autocomplete="off" spellcheck="false"
                                   role="combobox" aria-controls="matches" placeholder="Введите поисковый запрос"
                                   aria-expanded="false" aria-live="polite" name="search">
                        </div>
                    </div>
                    <div>
                        <button type="submit">Найти</button>
                    </div>
                </div>
            </form>
            <div class="header__log">
                {% if user.is_authenticated %}
                    <div class="header__log__container">
                        <a class="header__log-text" href="{% url 'logout' %}">Выйти</a>
                    </div>
                {% else %}
                    <div class="header__log__container">
                        <a class="header__log-text" href="{% url 'login' %}">Войти</a>
                    </div>
                {% endif %}
            </div>
        </header>
        <main>
            <div class="cards">
                <a href="{% url 'create_voting' %}">Здесь мог быть ваш новый опрос</a>
                <ul class="card__list">
                    {% for voting in user_voting %}
                        <li class="card__item">
                            <div class="card__container">
                                <div class="card__profile_image">
                                    <div class="card__profile_image__conteiner">
                                        <img src="{% static 'data\test.png' %}" alt="">
                                    </div>
                                </div>
                                <div class="card__information">
                                    <div class="card__title__container">
                                        <div class="card__title">{{ voting.author.username }}</div>
                                        <div class="card__type">Опрос</div>
                                    </div>
                                    <div class="card__description">{{ voting.title }}</div>
                                </div>
                                <div class="card__more">
                                    <a href="{% url 'voting_detail' voting.id %}">
                                        <div class="card__more__container">
                                            <img src="{% static 'data\more.svg' %}" alt="">
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <a class="edit_button" href="{% url 'edit_voting' voting.id %}">edit</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </main>
    </div>
</body>
</html>

voting_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
    <h2>Register</h2>
    <form method="post" action="{% url 'register' %}">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Register</button>
    </form>
  <a href="{% url 'login' %}">login</a>
  </body>
</html>